/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const Player = IDL.Record({
  'id' : IDL.Text,
  'hasRolled' : IDL.Bool,
  'name' : IDL.Text,
  'reputation' : IDL.Int,
  'innovation' : IDL.Int,
  'capital' : IDL.Int,
  'capacity' : IDL.Int,
  'position' : IDL.Nat,
});
export const GameState = IDL.Record({
  'gameStarted' : IDL.Bool,
  'currentTurn' : IDL.Nat,
  'players' : IDL.Vec(Player),
  'hostId' : IDL.Text,
  'gameFinished' : IDL.Bool,
  'roomCode' : IDL.Text,
  'round' : IDL.Nat,
});
export const TileType = IDL.Variant({
  'final' : IDL.Null,
  'decision' : IDL.Null,
  'penalty' : IDL.Null,
  'start' : IDL.Null,
  'bonus' : IDL.Null,
});
export const Tile = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'tileType' : TileType,
});

export const idlService = IDL.Service({
  'createGame' : IDL.Func([IDL.Text], [IDL.Text], []),
  'endTurn' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'getGameState' : IDL.Func([IDL.Text], [IDL.Opt(GameState)], ['query']),
  'getTile' : IDL.Func([IDL.Nat], [IDL.Opt(Tile)], ['query']),
  'joinGame' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'rollDice' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'startGame' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const Player = IDL.Record({
    'id' : IDL.Text,
    'hasRolled' : IDL.Bool,
    'name' : IDL.Text,
    'reputation' : IDL.Int,
    'innovation' : IDL.Int,
    'capital' : IDL.Int,
    'capacity' : IDL.Int,
    'position' : IDL.Nat,
  });
  const GameState = IDL.Record({
    'gameStarted' : IDL.Bool,
    'currentTurn' : IDL.Nat,
    'players' : IDL.Vec(Player),
    'hostId' : IDL.Text,
    'gameFinished' : IDL.Bool,
    'roomCode' : IDL.Text,
    'round' : IDL.Nat,
  });
  const TileType = IDL.Variant({
    'final' : IDL.Null,
    'decision' : IDL.Null,
    'penalty' : IDL.Null,
    'start' : IDL.Null,
    'bonus' : IDL.Null,
  });
  const Tile = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'tileType' : TileType,
  });
  
  return IDL.Service({
    'createGame' : IDL.Func([IDL.Text], [IDL.Text], []),
    'endTurn' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'getGameState' : IDL.Func([IDL.Text], [IDL.Opt(GameState)], ['query']),
    'getTile' : IDL.Func([IDL.Nat], [IDL.Opt(Tile)], ['query']),
    'joinGame' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'rollDice' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'startGame' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };