/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GameState {
  'gameStarted' : boolean,
  'currentTurn' : bigint,
  'players' : Array<Player>,
  'hostId' : string,
  'gameFinished' : boolean,
  'roomCode' : string,
  'round' : bigint,
}
export interface Player {
  'id' : string,
  'hasRolled' : boolean,
  'name' : string,
  'reputation' : bigint,
  'innovation' : bigint,
  'capital' : bigint,
  'capacity' : bigint,
  'position' : bigint,
}
export type Result = { 'ok' : string } |
  { 'err' : string };
export interface Tile { 'id' : bigint, 'name' : string, 'tileType' : TileType }
export type TileType = { 'final' : null } |
  { 'decision' : null } |
  { 'penalty' : null } |
  { 'start' : null } |
  { 'bonus' : null };
export interface _SERVICE {
  'createGame' : ActorMethod<[string], string>,
  'endTurn' : ActorMethod<[string, string], Result>,
  'getGameState' : ActorMethod<[string], [] | [GameState]>,
  'getTile' : ActorMethod<[bigint], [] | [Tile]>,
  'joinGame' : ActorMethod<[string, string], Result>,
  'rollDice' : ActorMethod<[string, string], Result>,
  'startGame' : ActorMethod<[string, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];